# Generated by Django 5.1.1 on 2024-09-14 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("public_addr", models.CharField(max_length=100)),
                ("position", models.TextField(blank=True, max_length=200)),
                ("info", models.TextField(blank=True, max_length=200)),
                ("Company_Name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("applied_verification", models.IntegerField(default=0)),
                ("verified", models.IntegerField(default=0)),
            ],
        ),
    ]
