# Generated by Django 5.1.1 on 2024-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signer",
            name="Company_Name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
