# Generated by Django 6.1 on 2026-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_signer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='applied_verification',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='signer',
            name='verified',
            field=models.IntegerField(default=1),
        ),
    ]
