# Generated by Django 6.1 on 2026-09-02 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_signer_applied_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_address', models.CharField(db_index=True, max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_hash', models.CharField(db_index=True, max_length=200)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('validator_name', models.CharField(blank=True, max_length=200)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
